package:
    name: mflow_nodes
    version: 0.0.3

build:
  number: 0

source:
    path: ..

requirements:
    build:
        - python
    run:
        - python
        - mflow >=0.0.16
        - bottle
        - numpy
        - requests

test:
  source_files:
    - tests/

about:
    summary: "mflow nodes is a library for building processing nodes on top of an mflow stream."
