package:
    name: mflow_nodes
    version: 1.0.0

build:
  number: 1

source:
    path: ..

requirements:
    build:
        - python
    run:
        - python
        - mflow >=0.0.17
        - bottle
        - numpy
        - requests
        - ujson

test:
  source_files:
    - tests/

about:
    summary: "mflow nodes is a library for building processing nodes on top of an mflow stream."
